version: 2

sources:
  - name: olist_dwh
    database: olist-pipeline-491503
    schema: olist_dwh
    tables:
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: customers
      - name: sellers
      - name: products
      - name: geolocation
      - name: category_translation